version: "2"
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: false

linters:
  enable:
    - gosec
    - err113
    - mnd
    - loggercheck
    - staticcheck
    - govet
  settings:
    govet:
      enable-all: true
    copyloopvar:
      check-alias: true
  exclusions:
    paths:
      - internal/db/generated

run:
  timeout: 5m
